### ISSUE TITLE
CSV upload & Gitlab management

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/wp4-csdh-api#10]
The API should provide operations to manage the upload of new CSV files to the HUB, making them accessible to e.g. QBer. This should act as a tunnel to Gitlab, where all persistent storage of datasets must be centralised.

**Comment by albertmeronyo** [comment]
Related to CLARIAH/qber#61

**Comment by RinkeHoekstra** [comment]
Closed with CLARIAH/wp4-requirements#17 and 982a651

Current implementation allows users to upload a dataset by providing a URL (e.g. a direct download link from Dropbox... this is what CLARIAH/qber#61 currently uses)
